global using Xunit;
global using Auth.Application.DTOs;
global using Auth.Application.Services;
global using Auth.Application.Settings;
global using Auth.Infrastructure.Persistence;
global using CopyTradeMarketApi.Shared.Abstractions;
global using CopyTradeMarketApi.Shared.Exceptions;
global using Microsoft.EntityFrameworkCore;
global using Moq;