<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\CopyTradeMarketApi.Shared\CopyTradeMarketApi.Shared.csproj" />
    <ProjectReference Include="..\..\Modules\Auth\Auth.API\Auth.API.csproj" />
    <ProjectReference Include="..\..\Modules\Tracking\Tracking.API\Tracking.API.csproj" />
    <ProjectReference Include="..\..\Modules\Affiliate\Affiliate.API\Affiliate.API.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Enrichers.Environment" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Serilog.Sinks.Grafana.Loki" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7e312891-5a63-4772-b1e0-2a615d643784</UserSecretsId>
  </PropertyGroup>

</Project>
