<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Auth.Domain\Auth.Domain.csproj" />
    <ProjectReference Include="..\Auth.Infrastructure\Auth.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Shared\CopyTradeMarketApi.Shared\CopyTradeMarketApi.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
